version: "3"

services:
  springboot-app:
    container_name: spring-app
    image: kanban
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - kanban-network

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  kanban-volume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: kanban
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kanban-network

volumes:
  kanban-volume:

networks:
  kanban-network: